### ISSUE TITLE
App crash while show tooltip 

### ISSUE THREAD

**Issue by monikasavaliya** [tomergoldst/tooltips#42]
java.lang.StringIndexOutOfBoundsException: length=0; index=0
	at java.lang.String.charAt(Native Method)
	at com.tomergoldst.tooltips.UiUtils.isRtl(UiUtils.java:28)
	at com.tomergoldst.tooltips.UiUtils.isRtl(UiUtils.java:24)
	at com.tomergoldst.tooltips.ToolTipsManager.create(ToolTipsManager.java:102)
	at com.tomergoldst.tooltips.ToolTipsManager.show(ToolTipsManager.java:69)

**Comment by aeropare-lab** [comment]
> java.lang.StringIndexOutOfBoundsException: length=0; index=0 at java.lang.String.charAt(Native Method) at com.tomergoldst.tooltips.UiUtils.isRtl(UiUtils.java:28) at com.tomergoldst.tooltips.UiUtils.isRtl(UiUtils.java:24) at com.tomergoldst.tooltips.ToolTipsManager.create(ToolTipsManager.java:102) at com.tomergoldst.tooltips.ToolTipsManager.show(ToolTipsManager.java:69)

**Comment by naveenchandan** [comment]
https://github.com/tomergoldst/tooltips/issues/43#issuecomment-1644468307
