### ISSUE TITLE
> java.lang.StringIndexOutOfBoundsException: length=0; index=0 at java.lang.String.charAt(Native Method) at com.tomergoldst.tooltips.UiUtils.isRtl(UiUtils.java:28) at com.tomergoldst.tooltips.UiUtils.isRtl(UiUtils.java:24) at com.tomergoldst.tooltips.ToolTipsManager.create(ToolTipsManager.java:102) at com.tomergoldst.tooltips.ToolTipsManager.show(ToolTipsManager.java:69)

### ISSUE THREAD

**Issue by aeropare-lab** [tomergoldst/tooltips#43]
> java.lang.StringIndexOutOfBoundsException: length=0; index=0 at java.lang.String.charAt(Native Method) at com.tomergoldst.tooltips.UiUtils.isRtl(UiUtils.java:28) at com.tomergoldst.tooltips.UiUtils.isRtl(UiUtils.java:24) at com.tomergoldst.tooltips.ToolTipsManager.create(ToolTipsManager.java:102) at com.tomergoldst.tooltips.ToolTipsManager.show(ToolTipsManager.java:69)

**Comment by aeropare-lab** [comment]
> > java.lang.StringIndexOutOfBoundsException: length=0; index=0 at java.lang.String.charAt(Native Method) at com.tomergoldst.tooltips.UiUtils.isRtl(UiUtils.java:28) at com.tomergoldst.tooltips.UiUtils.isRtl(UiUtils.java:24) at com.tomergoldst.tooltips.ToolTipsManager.create(ToolTipsManager.java:102) at com.tomergoldst.tooltips.ToolTipsManager.show(ToolTipsManager.java:69)

**Comment by naveenchandan** [comment]
Facing same crash, Please fix it on priority.
